apiVersion: v1
kind: Secret
metadata:
  name: flora-secrets
  namespace: chiloe-flora
type: Opaque
data:
  # Estos valores están en base64
  # DB_USER: postgres (cG9zdGdyZXM=)
  # DB_PASSWORD: postgres (cG9zdGdyZXM=)
  # JWT_SECRET: your-super-secret-jwt-key (eW91ci1zdXBlci1zZWNyZXQtand0LWtleQ==)
  # OBJECT_STORAGE_ACCESS_KEY: minioadmin (bWluaW9hZG1pbg==)
  # OBJECT_STORAGE_SECRET_KEY: minioadmin123 (bWluaW9hZG1pbjEyMw==)
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleQ==
  OBJECT_STORAGE_ACCESS_KEY: bWluaW9hZG1pbg==
  OBJECT_STORAGE_SECRET_KEY: bWluaW9hZG1pbjEyMw==
