apiVersion: v1
kind: Service
metadata:
  name: flora-api-service
  namespace: chiloe-flora
  labels:
    app: flora-api
spec:
  selector:
    app: flora-api
  ports:
    - port: 80
      targetPort: 9080
      protocol: TCP
      name: http
  type: ClusterIP